controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends FrontController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionRegistration()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new User();
//        $model->scenario = 'new_' . User::TYPE_CUSTOMER;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->encryptPassword();
            $model->save();

            // привязываем роль пользователю
            $authManager = \Yii::$app->authManager;
            if ($model->getIsCustomer()) {
                $customerRole = $authManager->getRole(User::TYPE_CUSTOMER);
                $authManager->assign($customerRole, $model->id);
            } elseif ($model->getIsPerformer()) {
                $performerRole = $authManager->getRole(User::TYPE_PERFORMER);
                $authManager->assign($performerRole, $model->id);
            }

            return $this->goBack();
        }

        return $this->render('registration', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/TaskController.php
<?php

namespace app\controllers;

use app\models\forms\PerformerForm;
use app\models\forms\TaskRespondForm;
use app\models\PerformerTaskRespond;
use app\models\User;
use Yii;
use app\models\Task;
use app\models\search\TaskSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends FrontController
{
    /**
     * Страница поиска задач исполнителем
     *
     * @return string
     */
    public function actionSearch()
    {
        $searchModel = new TaskSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->post());

        return $this->render('search', [
            'model' => new Task(),
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionView($id)
    {
        $request = Yii::$app->request;
        $task = $this->findModel($id);
        $taskRespondForm = new TaskRespondForm();
        $taskRespondForm->taskId = $task->id;

        if ($this->user && $this->user->getIsPerformer()) {
            $taskRespondForm->userId = $this->user->id;
        }

        // todo перенести код в event onView
        // просмотры
        $viewedTasks = Yii::$app->session->get('viewedTasks', []);
        if (!isset($viewedTasks[$task->id])) {
            $viewedTasks[$task->id] = time();
            Yii::$app->session->set('viewedTasks', $viewedTasks);

            $task->viewCount += 1;
            $task->uniqueViewCount += 1;
            $task->update(false);
        }

        if ($request->isPost) {
            // обработка отклика на задачу
            if ($formData = $request->post('TaskRespondForm')) {
                if ($taskRespondForm->load($request->post()) && $taskRespondForm->validate()) {
                    $performerTaskRespond = new PerformerTaskRespond();
                    $performerTaskRespond->setAttributes([
                        'taskId' => $taskRespondForm->taskId,
                        'performerId' => $taskRespondForm->userId,
                    ]);
                    $performerTaskRespond->insert();

                    $task->responseCount += 1;
                    $task->update(false);

                    // todo event - new respond created

                    Yii::$app->session->setFlash('respond_created_msg', Yii::t('app', 'New respond successfully created!'));
                    $this->refresh();
                }
            }
        }

        return $this->render('view', [
            'task' => $task,
            'taskRespondForm' => $taskRespondForm,
        ]);
    }

    /**
     * Finds the Task model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Task the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Task::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php
use app\models\User;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\helpers\AppAsset;

/**
 * @var \yii\web\View $this
 * @var string $content
 */
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->params['projectName'],
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);

        $menuItems = [
        ];

        if (Yii::$app->user->isGuest) {
            $menuItems[] = ['label' => \Yii::t('app', 'Sign In'), 'url' => ['/site/login']];
            $menuItems[] = ['label' => \Yii::t('app', 'Sign Up'), 'url' => ['/site/registration']];
        } else {
            /** @var User $userIdentity */
            $userIdentity = \Yii::$app->user->identity;

            if ($userIdentity->getIsCustomer()) {

                $newResponsesInfo = $userIdentity->getResponsesInfo();
                $responsesLabel = \Yii::t('app', 'Responses');
                if ($newResponsesInfo[\app\models\PerformerTaskRespond::STATUS_NEW]['count'] > 0) {
                    $responsesLabel .= ' <span class="badge">' . $newResponsesInfo[\app\models\PerformerTaskRespond::STATUS_NEW]['count'] . '</span>';
                }

                $menuItems[] = ['label' => $responsesLabel, 'url' => ['/customer/task/responses']];
                $menuItems[] = ['label' => \Yii::t('app', 'My tasks'), 'url' => ['/customer/task/index']];
            } elseif ($userIdentity->getIsPerformer()) {
                $menuItems[] = ['label' => \Yii::t('app', 'Search tasks'), 'url' => ['/task/search']];
                $menuItems[] = ['label' => \Yii::t('app', 'My tasks'), 'url' => ['/performer/task/index']];
            }
            $menuItems[] = ['label' => \Yii::t('app', 'Sign Out'), 'url' => ['/site/logout'], 'linkOptions' => ['data-method' => 'post']];
        }

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $menuItems,
            'encodeLabels' => false,
        ]);
        NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'homeLink' => [
                    'label' => 'Главная',
                    'url' => Yii::$app->homeUrl,
                ],
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>